### ISSUE TITLE
Add page catch route

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/seattle_v2#69]
## Use Case
*Please provide a use case to help us understand your request in context*
We are experiencing breaks on the database / pipeline that cause downstream effects for the front end. In the case that I don't see an error occurred on the pipeline (during the dask + prefect pipeline rewrite we will add slack notifications to the pipeline), the user should be aware that something went wrong and be asked to alert us. 

## Solution
*Please describe your ideal solution*
It would be great if we could just detect critical errors? I don't know how to do that but in the case we can, reroute to a page that says "Something went wrong, we would really appreciate you filling out an issue so we can address it soon :)"

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Fix the pipeline to actually alert us on slack. (I'm working on it)

**Comment by tohuynh** [comment]
What are some examples of critical errors?

Right now, I'm showing the error msg for any errors that occur because of inconsistent data from the database. If db.selectRowbById return an undefined value, I'll show the error msg. I also have errors for a transcript that don't exist or failed to download transcript content.

In general, if any of API calls have an error, I'll show the error msg.

I am using [Error Boundary](https://reactjs.org/docs/error-boundaries.html) to show the error msg. `<ErrorBoundary><Component/></ErrorBoundary>` means that if the inside component  has any errors, ErrorBoundary will show the error msg. I have the ErrorBoundary wrapped around all the components in /pages dir and also App.js. Basically, I catch and show error msg for almost all errors.

Are there any errors that we don't want to show the error msg?
